import {db,bucket,config} from '@/db/runtime';
import {getChatGPTUser} from '@/app/chatgpt-auth';
export const dynamic='force-dynamic';
type Row=Record<string,any>;
const now=()=>new Date().toISOString();
const num=(d:Row,k:string,min=0)=>{const v=Number(d[k]);if(!Number.isSafeInteger(v)||v<min||v>1000000)throw Error('Quantidade inválida: '+k);return v};
const str=(d:Row,k:string,max=200,required=true)=>{if(typeof d[k]!=='string'||d[k].length>max||(required&&!d[k].trim()))throw Error('Confira o campo '+k);return d[k].trim()};
const money=(d:Row,k:string,positive=false)=>{const v=String(d[k]).replace(',','.');if(!/^\d{1,7}(\.\d{1,2})?$/.test(v))throw Error('Valor inválido: '+k);const cents=Math.round(Number(v)*100);if(positive&&cents===0)throw Error('Valor deve ser maior que zero.');return cents};
const validEmail=(d:Row)=>{let v=str(d,'email').toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))throw Error('E-mail inválido.');return v};
const sha=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const token=()=>crypto.randomUUID()+crypto.randomUUID();
function json(data:any,status=200,cookie?:string){return Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...(cookie?{'Set-Cookie':cookie}:{})}})}
const failure=(error:string,status=400)=>json({error},status);
const statement=(sql:string,...args:any[])=>db().prepare(sql).bind(...args);
const rows=async(sql:string,...args:any[])=>(await statement(sql,...args).all<Row>()).results;
const one=async(sql:string,...args:any[])=>statement(sql,...args).first<Row>();
async function record(table:string,id:number){const r=await one(`SELECT * FROM ${table} WHERE id=?`,id);if(!r)throw Error('Registro não encontrado.');return r}
async function identity(){const auth=await getChatGPTUser();if(!auth)return null;const owner=auth.email.toLowerCase()===config().OWNER_EMAIL?.toLowerCase();let u=await one('SELECT * FROM users WHERE auth_id=?',auth.userId);if(!u){await statement('INSERT INTO users(auth_id,name,email,role) VALUES(?,?,?,?) ON CONFLICT(email) DO UPDATE SET auth_id=excluded.auth_id WHERE users.auth_id IS NULL',auth.userId,auth.fullName||auth.email,auth.email.toLowerCase(),owner?'admin':'customer').run();u=await one('SELECT * FROM users WHERE auth_id=?',auth.userId)}if(!u)throw Error('Conta vinculada a outro acesso.');if(owner&&u.role!=='admin'){await statement("UPDATE users SET role='admin',active=1 WHERE id=?",u.id).run();u.role='admin';u.active=1}if(!u.active)throw Error('Conta desativada. Entre em contato com a loja.');return u}
async function session(req:Request){const match=(req.headers.get('cookie')||'').match(/(?:^|;\s*)anna_session=([a-f0-9-]{72})/);let raw=match?.[1]||'',hash=raw?await sha(raw):'',s=hash?await one('SELECT * FROM sessions WHERE token=? AND expires>?',hash,Date.now()):null;let cookie='';if(!s){raw=token();hash=await sha(raw);s={token:hash,csrf:token(),expires:Date.now()+30*86400000};await statement('INSERT INTO sessions(token,csrf,expires) VALUES(?,?,?)',hash,s.csrf,s.expires).run();cookie=`anna_session=${raw}; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=2592000`}return {s,cookie}}
async function cancelOrders(id:number|null){const op=crypto.randomUUID();const condition=id!==null?"id=? AND status!='cancelled' AND (invoice_key IS NULL OR invoice_cancelled=1)":"status='pending' AND created<?";const value=id!==null?id:new Date(Date.now()-48*3600000).toISOString();await db().batch([
 statement("UPDATE orders SET status='cancelled',cancelled_at=?,cancel_op=? WHERE "+condition,now(),op,value),
 statement('UPDATE products SET stock=stock+(SELECT SUM(i.quantity) FROM items i JOIN orders o ON o.id=i.order_id WHERE o.cancel_op=? AND i.product_id=products.id),version=version+1 WHERE id IN(SELECT i.product_id FROM items i JOIN orders o ON o.id=i.order_id WHERE o.cancel_op=?)',op,op),
 statement("INSERT INTO movements(product_id,date,delta,reason) SELECT i.product_id,?,i.quantity,'Cancelamento #'||o.id FROM items i JOIN orders o ON o.id=i.order_id WHERE o.cancel_op=?",now(),op)
]);}
async function cleanup(){await cancelOrders(null)}
function own(o:Row,u:Row|null,s:Row){return u?.role==='admin'||(u&&o.customer_id===u.id)||(!o.customer_id&&o.guest_id===s.token)}
export async function GET(req:Request){try{const path=new URL(req.url).pathname.split('/').pop();if(path==='photo'){const key=new URL(req.url).searchParams.get('key')||'';if(!/^photos\/[a-f0-9-]+\.(png|jpeg|webp)$/.test(key))return failure('Imagem inválida.',404);const object=await bucket().get(key);if(!object)return failure('Imagem não encontrada.',404);return new Response(object.body,{headers:{'Content-Type':object.httpMetadata?.contentType||'image/jpeg','Cache-Control':'public,max-age=86400','X-Content-Type-Options':'nosniff'}})}const u=await identity(),admin=u?.role==='admin';const {s,cookie}=await session(req);
if(path==='state'){await cleanup();if(u)await statement('UPDATE orders SET customer_id=? WHERE customer_id IS NULL AND guest_id=?',u.id,s.token).run();const settings=await one('SELECT * FROM settings WHERE id=1')||{contact:'',pickup:'',open:0};const products=await rows('SELECT '+(admin?'*':'id,sku,name,category,description,price,stock,active,photo')+' FROM products'+(admin?'':' WHERE active=1')+' ORDER BY name');let orders=await rows('SELECT * FROM orders'+(admin?'':u?' WHERE customer_id=?':' WHERE guest_id=? AND customer_id IS NULL')+' ORDER BY id DESC',...(admin?[]:u?[u.id]:[s.token]));for(const o of orders){o.items=await rows('SELECT product_id,name,quantity,price'+(admin?',cost':'')+' FROM items WHERE order_id=?',o.id);delete o.cancel_op;delete o.guest_id;delete o.ip_hash;delete o.request_id;delete o.invoice_file;delete o.cancel_file;if(!admin)delete o.cost}return json({setup:false,user:u?{id:u.id,name:u.name,email:u.email,role:u.role}:null,csrf:s.csrf,products,orders,expenses:admin?await rows('SELECT * FROM expenses ORDER BY date DESC,id DESC'):[],users:admin?await rows('SELECT id,name,email,role,active FROM users ORDER BY name'):[],movements:admin?await rows('SELECT m.*,p.name FROM movements m JOIN products p ON p.id=m.product_id ORDER BY m.id DESC LIMIT 100'):[],settings},200,cookie)}
if(path==='invoice-download'){const o=await record('orders',Number(new URL(req.url).searchParams.get('id')));if(!own(o,u,s))return failure('Acesso não permitido.',403);if(!o.invoice_file)return failure('Nenhum XML anexado.',404);const file=await bucket().get(o.invoice_file);if(!file)return failure('Arquivo não encontrado.',404);return new Response(file.body,{headers:{'Content-Type':'application/xml','Content-Disposition':`attachment; filename="nota-${o.id}.xml"`,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}})}
if(path==='backup'){if(!admin)return failure('Somente administradores.',403);const exportData:Row={version:2,created:now(),notice:'Exportação de dados; fotos e XMLs permanecem no armazenamento do site.'};for(const table of ['users','products','orders','items','expenses','movements','settings'])exportData[table]=await rows('SELECT * FROM '+table);return new Response(JSON.stringify(exportData,null,2),{headers:{'Content-Type':'application/json','Content-Disposition':'attachment; filename="anna-dados.json"','Cache-Control':'no-store'}})}return failure('Página não encontrada.',404)}catch(e){console.error(e);return failure('Não foi possível carregar. Tente atualizar a página.',503)}}
export async function POST(req:Request){try{if(req.headers.get('Origin')!==new URL(req.url).origin)return failure('Origem não permitida.',403);if(!req.headers.get('content-type')?.startsWith('application/json'))return failure('Formato inválido.',415);const length=Number(req.headers.get('content-length')||0);if(length>4000000)return failure('Arquivo muito grande.',413);const raw=await req.text();if(raw.length>4000000)return failure('Arquivo muito grande.',413);const d:Row=JSON.parse(raw);if(!d||typeof d!=='object'||Array.isArray(d))return failure('Dados inválidos.');const u=await identity(),admin=u?.role==='admin';const {s}=await session(req);if(req.headers.get('X-CSRF-Token')!==s.csrf)return failure('Sessão expirada. Atualize a página.',403);const path=new URL(req.url).pathname.split('/').pop();
if(path==='logout'){await statement('DELETE FROM sessions WHERE token=?',s.token).run();return json({ok:true},200,'anna_session=; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=0')}
if(path==='orders'){await cleanup();if(!admin){const settings=await one('SELECT * FROM settings WHERE id=1');if(!settings?.open)return failure('A loja ainda não está recebendo pedidos.');}
const requestId=str(d,'request_id',100);if(!/^[a-f0-9-]{36}$/.test(requestId))throw Error('Identificação inválida.');const prior=await one('SELECT * FROM orders WHERE request_id=?',requestId);if(prior){if(!own(prior,u,s))return failure('Pedido não permitido.',403);return json({ok:true,id:prior.id})}
const ipHash=await sha((config().SESSION_SECRET||'')+(req.headers.get('cf-connecting-ip')||s.token));if(!admin){const recent=await one('SELECT COUNT(*) AS count FROM orders WHERE (guest_id=? OR ip_hash=?) AND created>?',s.token,ipHash,new Date(Date.now()-3600000).toISOString());if(recent&&recent.count>=10)return failure('Limite de pedidos nesta hora. Entre em contato com a loja.',429)}
if(!Array.isArray(d.items)||d.items.length<1||d.items.length>50)throw Error('Selecione os produtos.');const merged=new Map<number,number>();for(const item of d.items){const id=num(item,'id',1),q=num(item,'quantity',1);merged.set(id,(merged.get(id)||0)+q)}const chosen:Row[]=[];for(const [id,q]of merged){const p=await record('products',id);if(!p.active||p.stock<q)throw Error('Estoque insuficiente para '+p.name);chosen.push({...p,quantity:q})}const total=chosen.reduce((a,p)=>a+p.price*p.quantity,0),cost=chosen.reduce((a,p)=>a+p.cost*p.quantity,0);let customerId=u?.id||null,customerName=str(d,'customer_name');if(admin){customerId=num(d,'customer_id')||null;if(customerId){const customer=await record('users',customerId);if(!customer.active)throw Error('Cliente desativado.');customerName=customer.name}}
const phone=str(d,'phone',30,!admin);if(phone&&!/^\+?[\d\s()-]{10,25}$/.test(phone))throw Error('Informe o telefone com DDD.');const email=str({...d,email:d.email||u?.email||''},'email',200,false);const delivery=str({...d,delivery:d.delivery||'Retirada a combinar'},'delivery',500);const payment=str(d,'payment',40);if(!['Pix','Dinheiro','Cartão','A combinar'].includes(payment))throw Error('Forma de pagamento inválida.');const paid=admin&&d.paid===true,stamp=now();const statements=[statement('INSERT INTO orders(customer_id,guest_id,customer_name,phone,email,delivery,created,paid_at,status,payment,total,cost,request_id,ip_hash) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',customerId,s.token,customerName,phone,email,delivery,stamp,paid?stamp:null,paid?'paid':'pending',payment,total,cost,requestId,ipHash)];for(const p of chosen){statements.push(statement('UPDATE products SET stock=CASE WHEN active=1 AND price=? AND cost=? THEN stock-? ELSE -1 END,version=version+1 WHERE id=?',p.price,p.cost,p.quantity,p.id));statements.push(statement('INSERT INTO items(order_id,product_id,name,quantity,price,cost) SELECT id,?,?,?,?,? FROM orders WHERE request_id=?',p.id,p.name,p.quantity,p.price,p.cost,requestId));statements.push(statement("INSERT INTO movements(product_id,date,delta,reason) SELECT ?,?,?,'Pedido #'||id FROM orders WHERE request_id=?",p.id,stamp,-p.quantity,requestId));}try{await db().batch(statements)}catch(error){const dup=await one('SELECT * FROM orders WHERE request_id=?',requestId);if(dup&&own(dup,u,s))return json({ok:true,id:dup.id});throw error}const order=await one('SELECT id FROM orders WHERE request_id=?',requestId);return json({ok:true,id:order?.id})}
if(!admin)return failure('Somente administradores.',403);
if(path==='products'){const id=num(d,'id'),old=id?await record('products',id):null;let photo=str({...d,photo:d.photo||''},'photo',3000000,false);if(photo.startsWith('data:')){const m=photo.match(/^data:image\/(png|jpeg|webp);base64,([A-Za-z0-9+/=]+)$/);if(!m)throw Error('Foto inválida.');const bytes=Uint8Array.from(atob(m[2]),x=>x.charCodeAt(0));if(bytes.length>2000000)throw Error('Foto maior que 2 MB.');const valid=m[1]==='png'?bytes[0]===137&&bytes[1]===80:m[1]==='jpeg'?bytes[0]===255&&bytes[1]===216:bytes[0]===82&&bytes[1]===73;if(!valid)throw Error('Formato de imagem inválido.');const key='photos/'+crypto.randomUUID()+'.'+m[1];await bucket().put(key,bytes,{httpMetadata:{contentType:'image/'+m[1]}});photo='/api/photo?key='+key}else if(photo&&photo!==old?.photo)throw Error('Envie uma foto pelo formulário.');const stock=num(d,'stock');const fields=[str(d,'sku',60),str(d,'name'),str(d,'category',80),str({...d,description:d.description||''},'description',2000,false),money(d,'price',true),money(d,'cost'),stock,num(d,'minimum'),d.active?1:0,photo];if(old){const version=num(d,'version',1);const result=await statement('UPDATE products SET sku=?,name=?,category=?,description=?,price=?,cost=?,stock=?,minimum=?,active=?,photo=?,version=version+1 WHERE id=? AND version=?',...fields,id,version).run();if(!result.meta.changes)throw Error('O produto mudou. Atualize a página antes de editar novamente.');if(stock!==old.stock)await statement('INSERT INTO movements(product_id,date,delta,reason) VALUES(?,?,?,?)',id,now(),stock-old.stock,str(d,'reason')).run();return json({ok:true,id})}const result=await statement('INSERT INTO products(sku,name,category,description,price,cost,stock,minimum,active,photo) VALUES(?,?,?,?,?,?,?,?,?,?)',...fields).run();if(stock)await statement('INSERT INTO movements(product_id,date,delta,reason) VALUES(?,?,?,?)',result.meta.last_row_id,now(),stock,'Estoque inicial').run();return json({ok:true,id:result.meta.last_row_id})}
if(path==='pay'||path==='cancel'){const o=await record('orders',num(d,'id',1));if(path==='pay'){if(o.status!=='pending')throw Error('Somente pedidos pendentes podem ser recebidos.');const r=await statement("UPDATE orders SET status='paid',paid_at=? WHERE id=? AND status='pending'",now(),o.id).run();if(!r.meta.changes)throw Error('Pedido já atualizado.')}else{if(o.status==='cancelled')throw Error('Pedido já cancelado.');if(o.invoice_key&&!o.invoice_cancelled)throw Error('Vincule primeiro o cancelamento fiscal.');await cancelOrders(o.id)}return json({ok:true})}
if(path==='expenses'){const date=str(d,'date',10);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||new Date(date+'T12:00:00Z').toISOString().slice(0,10)!==date)throw Error('Data inválida.');if(!['stock','operating'].includes(d.kind))throw Error('Tipo inválido.');await statement('INSERT INTO expenses(date,description,category,kind,amount) VALUES(?,?,?,?,?)',date,str(d,'description'),str(d,'category',80),d.kind,money(d,'amount',true)).run();return json({ok:true})}
if(path==='expense-void'){await statement('UPDATE expenses SET void=1 WHERE id=?',num(d,'id',1)).run();return json({ok:true})}
if(path==='users'){const email=validEmail(d),role=str(d,'role',20);if(!['admin','customer'].includes(role))throw Error('Perfil inválido.');await statement('INSERT INTO users(name,email,role) VALUES(?,?,?)',str(d,'name'),email,role).run();return json({ok:true})}
if(path==='user-active'){const id=num(d,'id',1);if(id===u.id)throw Error('Você não pode desativar sua própria conta.');const target=await record('users',id);if(target.email.toLowerCase()===config().OWNER_EMAIL?.toLowerCase())throw Error('O proprietário não pode ser desativado.');await statement('UPDATE users SET active=? WHERE id=?',d.active?1:0,id).run();return json({ok:true})}
if(path==='settings'){const contact=str(d,'contact',30),pickup=str(d,'pickup',500);if(!/^\d{10,15}$/.test(contact.replace(/\D/g,'')))throw Error('Informe WhatsApp com código do país e DDD.');await statement('INSERT INTO settings(id,contact,pickup,open) VALUES(1,?,?,?) ON CONFLICT(id) DO UPDATE SET contact=excluded.contact,pickup=excluded.pickup,open=excluded.open',contact.replace(/\D/g,''),pickup,d.open?1:0).run();return json({ok:true})}
if(path==='invoice'||path==='invoice-cancel'){const o=await record('orders',num(d,'id',1));if(o.status!=='paid')throw Error('A venda deve estar recebida.');const xml=str(d,'xml',1000000);if(/<!DOCTYPE|<!ENTITY/i.test(xml)||!xml.includes('http://www.portalfiscal.inf.br/nfe'))throw Error('XML fiscal inválido.');const match=(tag:string)=>xml.match(new RegExp('<(?:\\w+:)?'+tag+'(?:\\s[^>]*)?>([^<]+)</(?:\\w+:)?'+tag+'>'))?.[1];const key=match('chNFe');if(!key||!/^\d{44}$/.test(key)||match('tpAmb')!=='1')throw Error('Use o XML processado de produção.');if(path==='invoice'){if(o.invoice_key)throw Error('Já existe XML vinculado.');if(match('cStat')!=='100'||!xml.includes('NFe'+key)||money({v:match('vNF')},'v')!==o.total)throw Error('Confira protocolo e valor do XML.');const file='invoices/'+o.id+'/'+crypto.randomUUID()+'.xml';await bucket().put(file,xml,{httpMetadata:{contentType:'application/xml'}});await statement('UPDATE orders SET invoice_key=?,invoice_file=? WHERE id=? AND invoice_key IS NULL',key,file,o.id).run()}else{if(key!==o.invoice_key||match('tpEvento')!=='110111'||!['135','155'].includes(match('cStat')||''))throw Error('Use o evento de cancelamento autorizado da mesma nota.');const file='invoices/'+o.id+'/cancel-'+crypto.randomUUID()+'.xml';await bucket().put(file,xml,{httpMetadata:{contentType:'application/xml'}});await statement('UPDATE orders SET invoice_cancelled=1,cancel_file=? WHERE id=?',file,o.id).run()}return json({ok:true})}
return failure('Operação não encontrada.',404)}catch(e){const message=e instanceof Error?e.message:'Não foi possível concluir.';console.error(e);if((message.includes('STOCK_OR_PRICE_CHANGED')||message.includes('nonnegative_stock')))return failure('O estoque ou preço mudou. Atualize a página e revise a sacola.',409);if(message.includes('UNIQUE constraint'))return failure('Já existe um registro com esse código ou e-mail.',409);if(message.includes('D1_')||message.includes('SQLITE_'))return failure('Não foi possível salvar. Atualize a página e tente novamente.',503);return failure(message)}}
